apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlserver-data-persisent-volume-claim
spec:
  storageClassName: database-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi